#!/usr/bin/env bash

osascript <<'EOF'
tell application "System Events"
    set frontApp to first application process whose frontmost is true
    tell frontApp
        try
            set win to front window
            set winSize to size of win
            set winW to item 1 of winSize
            set winH to item 2 of winSize
        on error
            return
        end try
    end tell
end tell

tell application "Finder"
    set screenBounds to bounds of window of desktop
end tell

set screenW to item 3 of screenBounds
set screenH to item 4 of screenBounds

set newX to (screenW - winW) / 2
set newY to (screenH - winH) / 2

tell application "System Events"
    tell frontApp
        set position of front window to {newX, newY}
    end tell
end tell
EOF
