[module/network]
type = internal/network

interface = wlan0
interval = 1.0

accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-perfix =  
format-disconnected = <label-disconnected>

; label-connected = %downspeed:9%
; label-disconnected = %downspeed:9%
ramp-signal = "%downspeed% %{A}"
label-connected = "    %downspeed%%{A}"
label-disconnected = "󰖪 "
click-left = exec "kitty -c 'nmtui'"
